site_name: "BandAid"
theme:
  name: "material"
  palette:
    scheme: default  # Dark mode (change to "default" for light mode)
  features:
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight

# Enable Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true  # Enables LaTeX rendering

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - awesome-pages
